<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Edas\V20170801\Models\InsertK8sApplicationResponseBody;

use AlibabaCloud\Tea\Model;

class applicationInfo extends Model
{
    /**
     * @description The ID of the application. You can call the ListApplication operation to query the application ID. For more information, see [ListApplication](~~149390~~).
     *
     * @example e83acea6-****-47e1-96ae-c0e95377****
     *
     * @var string
     */
    public $appId;

    /**
     * @description The name of the application.
     *
     * @example test
     *
     * @var string
     */
    public $appName;

    /**
     * @description The ID of the change process. You can call the GetChangeOrderInfo operation to query the change process ID. For more information, see [GetChangeOrderInfo](~~62072~~).
     *
     * @example cd65b247-****-475b-ad4b-7039040d625c
     *
     * @var string
     */
    public $changeOrderId;

    /**
     * @description The type of the cluster. Valid values:
     *
     *   0: regular Docker cluster
     *   1: Swarm cluster (discontinued)
     *   2: Elastic Compute Service (ECS) cluster
     *   3: self-managed Kubernetes cluster in EDAS (discontinued)
     *   4: cluster in which Pandora automatically registers applications
     *   5: ACK cluster and serverless Kubernetes cluster
     *
     * @example 5
     *
     * @var int
     */
    public $clusterType;

    /**
     * @description Indicates whether the application is a Docker application.
     *
     *   true: The application is a Docker application.
     *   false: The application is not a Docker application.
     *
     * @example true
     *
     * @var bool
     */
    public $dockerize;

    /**
     * @description The ID of the user to which the application belongs. This ID is generated by EDAS.
     *
     * @example 1172****6608****
     *
     * @var string
     */
    public $edasId;

    /**
     * @description The owner of the application.
     *
     * @example zp
     *
     * @var string
     */
    public $owner;

    /**
     * @description The ID of the region.
     *
     * @example cn-beijing
     *
     * @var string
     */
    public $regionId;

    /**
     * @description The ID of the Alibaba Cloud account to which the application belongs.
     *
     * @example edas_test****@aliyun****.com
     *
     * @var string
     */
    public $userId;
    protected $_name = [
        'appId'         => 'AppId',
        'appName'       => 'AppName',
        'changeOrderId' => 'ChangeOrderId',
        'clusterType'   => 'ClusterType',
        'dockerize'     => 'Dockerize',
        'edasId'        => 'EdasId',
        'owner'         => 'Owner',
        'regionId'      => 'RegionId',
        'userId'        => 'UserId',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->appId) {
            $res['AppId'] = $this->appId;
        }
        if (null !== $this->appName) {
            $res['AppName'] = $this->appName;
        }
        if (null !== $this->changeOrderId) {
            $res['ChangeOrderId'] = $this->changeOrderId;
        }
        if (null !== $this->clusterType) {
            $res['ClusterType'] = $this->clusterType;
        }
        if (null !== $this->dockerize) {
            $res['Dockerize'] = $this->dockerize;
        }
        if (null !== $this->edasId) {
            $res['EdasId'] = $this->edasId;
        }
        if (null !== $this->owner) {
            $res['Owner'] = $this->owner;
        }
        if (null !== $this->regionId) {
            $res['RegionId'] = $this->regionId;
        }
        if (null !== $this->userId) {
            $res['UserId'] = $this->userId;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return applicationInfo
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['AppId'])) {
            $model->appId = $map['AppId'];
        }
        if (isset($map['AppName'])) {
            $model->appName = $map['AppName'];
        }
        if (isset($map['ChangeOrderId'])) {
            $model->changeOrderId = $map['ChangeOrderId'];
        }
        if (isset($map['ClusterType'])) {
            $model->clusterType = $map['ClusterType'];
        }
        if (isset($map['Dockerize'])) {
            $model->dockerize = $map['Dockerize'];
        }
        if (isset($map['EdasId'])) {
            $model->edasId = $map['EdasId'];
        }
        if (isset($map['Owner'])) {
            $model->owner = $map['Owner'];
        }
        if (isset($map['RegionId'])) {
            $model->regionId = $map['RegionId'];
        }
        if (isset($map['UserId'])) {
            $model->userId = $map['UserId'];
        }

        return $model;
    }
}
