<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Dysmsapi\V20170525\Models;

use AlibabaCloud\Tea\Model;

class UpdateSmsTemplateResponseBody extends Model
{
    /**
     * @description Request status code.
     *
     * OK indicates a successful request.
     * For other error codes, refer to the **Error Codes** section of this chapter or the product\\"s [API Error Codes](https://help.aliyun.com/document_detail/101346.html).
     *
     * @example OK
     *
     * @var string
     */
    public $code;

    /**
     * @description Description of the status code.
     *
     * @example OK
     *
     * @var string
     */
    public $message;

    /**
     * @description Work order number.
     *
     * This parameter is used by auditors when querying audits. You need to provide this work order number when requesting expedited review.
     * @example 20041271****
     *
     * @var string
     */
    public $orderId;

    /**
     * @description The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot and locate issues.
     *
     * @example 819BE656-D2E0-4858-8B21-B2E477085AAF
     *
     * @var string
     */
    public $requestId;

    /**
     * @description Code of the SMS template.
     *
     * @example SMS_152550****
     *
     * @var string
     */
    public $templateCode;

    /**
     * @description Name of the SMS template.
     *
     * @example 验证码
     *
     * @var string
     */
    public $templateName;
    protected $_name = [
        'code'         => 'Code',
        'message'      => 'Message',
        'orderId'      => 'OrderId',
        'requestId'    => 'RequestId',
        'templateCode' => 'TemplateCode',
        'templateName' => 'TemplateName',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->code) {
            $res['Code'] = $this->code;
        }
        if (null !== $this->message) {
            $res['Message'] = $this->message;
        }
        if (null !== $this->orderId) {
            $res['OrderId'] = $this->orderId;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->templateCode) {
            $res['TemplateCode'] = $this->templateCode;
        }
        if (null !== $this->templateName) {
            $res['TemplateName'] = $this->templateName;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return UpdateSmsTemplateResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['Code'])) {
            $model->code = $map['Code'];
        }
        if (isset($map['Message'])) {
            $model->message = $map['Message'];
        }
        if (isset($map['OrderId'])) {
            $model->orderId = $map['OrderId'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['TemplateCode'])) {
            $model->templateCode = $map['TemplateCode'];
        }
        if (isset($map['TemplateName'])) {
            $model->templateName = $map['TemplateName'];
        }

        return $model;
    }
}
