<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Dysmsapi\V20170525\Models;

use AlibabaCloud\Tea\Model;

class UpdateSmsSignResponseBody extends Model
{
    /**
     * @description Request status code.
     *
     * OK indicates a successful request.
     * For other error codes, refer to [Error Code List](https://help.aliyun.com/document_detail/101346.html).
     *
     * @example OK
     *
     * @var string
     */
    public $code;

    /**
     * @description Description of the status code.
     *
     * @example OK
     *
     * @var string
     */
    public $message;

    /**
     * @description Work order number.
     *
     * This parameter is used by auditors when querying audits. You need to provide this work order number for expedited review.
     * @example 2004417****
     *
     * @var string
     */
    public $orderId;

    /**
     * @description The ID of this call request, uniquely generated by Alibaba Cloud, which can be used for troubleshooting and issue localization.
     *
     * @example A90E4451-FED7-49D2-87C8-00700A8C4D0D
     *
     * @var string
     */
    public $requestId;

    /**
     * @description The modified signature name.
     *
     * @example 登录验证
     *
     * @var string
     */
    public $signName;
    protected $_name = [
        'code'      => 'Code',
        'message'   => 'Message',
        'orderId'   => 'OrderId',
        'requestId' => 'RequestId',
        'signName'  => 'SignName',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->code) {
            $res['Code'] = $this->code;
        }
        if (null !== $this->message) {
            $res['Message'] = $this->message;
        }
        if (null !== $this->orderId) {
            $res['OrderId'] = $this->orderId;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->signName) {
            $res['SignName'] = $this->signName;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return UpdateSmsSignResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['Code'])) {
            $model->code = $map['Code'];
        }
        if (isset($map['Message'])) {
            $model->message = $map['Message'];
        }
        if (isset($map['OrderId'])) {
            $model->orderId = $map['OrderId'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['SignName'])) {
            $model->signName = $map['SignName'];
        }

        return $model;
    }
}
