<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Agency\V20221216\Models;

use AlibabaCloud\SDK\Agency\V20221216\Models\GetAccountInfoResponseBody\accountInfoList;
use AlibabaCloud\SDK\Agency\V20221216\Models\GetAccountInfoResponseBody\pageInfo;
use AlibabaCloud\Tea\Model;

class GetAccountInfoResponseBody extends Model
{
    /**
     * @description List of Account Information
     *
     * @var accountInfoList
     */
    public $accountInfoList;

    /**
     * @description Result Code - Error Code. Value Range:
     * - 3063: UserType value out of range.
     * @example 200
     *
     * @var string
     */
    public $code;

    /**
     * @description Message
     *
     * @example Success
     *
     * @var string
     */
    public $message;

    /**
     * @description Pagination Information
     *
     * @var pageInfo
     */
    public $pageInfo;

    /**
     * @description Request ID, the unique request identifier generated by Alibaba Cloud.
     *
     * @example 9C14ADFE-DF0A-54D4-8BD5-45D0839246B4
     *
     * @var string
     */
    public $requestId;

    /**
     * @description Candidate Value: True/False, which indicates whether the current API call itself is successful. It does not guarantee the success of subsequent business operations.
     *
     * @example true
     *
     * @var bool
     */
    public $success;
    protected $_name = [
        'accountInfoList' => 'AccountInfoList',
        'code'            => 'Code',
        'message'         => 'Message',
        'pageInfo'        => 'PageInfo',
        'requestId'       => 'RequestId',
        'success'         => 'Success',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->accountInfoList) {
            $res['AccountInfoList'] = null !== $this->accountInfoList ? $this->accountInfoList->toMap() : null;
        }
        if (null !== $this->code) {
            $res['Code'] = $this->code;
        }
        if (null !== $this->message) {
            $res['Message'] = $this->message;
        }
        if (null !== $this->pageInfo) {
            $res['PageInfo'] = null !== $this->pageInfo ? $this->pageInfo->toMap() : null;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->success) {
            $res['Success'] = $this->success;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return GetAccountInfoResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['AccountInfoList'])) {
            $model->accountInfoList = accountInfoList::fromMap($map['AccountInfoList']);
        }
        if (isset($map['Code'])) {
            $model->code = $map['Code'];
        }
        if (isset($map['Message'])) {
            $model->message = $map['Message'];
        }
        if (isset($map['PageInfo'])) {
            $model->pageInfo = pageInfo::fromMap($map['PageInfo']);
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['Success'])) {
            $model->success = $map['Success'];
        }

        return $model;
    }
}
