<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\CloudAPI\V20160714\Models;

use AlibabaCloud\SDK\CloudAPI\V20160714\Models\DescribeApiGroupResponseBody\customDomains;
use AlibabaCloud\SDK\CloudAPI\V20160714\Models\DescribeApiGroupResponseBody\stageItems;
use AlibabaCloud\Tea\Model;

class DescribeApiGroupResponseBody extends Model
{
    /**
     * @description The root path of the API.
     *
     * @example /qqq
     *
     * @var string
     */
    public $basePath;

    /**
     * @description The billing status of the API group.
     *
     *   **NORMAL**: The API group is normal.
     *   **LOCKED**: The API group is locked due to overdue payments.
     *
     * @example NORMAL
     *
     * @var string
     */
    public $billingStatus;

    /**
     * @description The products on Alibaba Cloud Marketplace.
     *
     * @example false
     *
     * @var bool
     */
    public $cloudMarketCommodity;

    /**
     * @description The CloudMonitor application group.
     *
     * @example 217008423
     *
     * @var string
     */
    public $cmsMonitorGroup;

    /**
     * @description The list of associated tags. Separate multiple tags with commas (,).
     *
     * @example depart:dep1
     *
     * @var string
     */
    public $compatibleFlags;

    /**
     * @description The creation time (UTC) of the API group.
     *
     * @example 2016-08-01T06:53:02Z
     *
     * @var string
     */
    public $createdTime;

    /**
     * @description The details about the custom domain name.
     *
     * @var customDomains
     */
    public $customDomains;

    /**
     * @description The custom trace configuration.
     *
     * @example {\\"parameterLocation\\":\\"HEADER\\",\\"parameterName\\":\\"traceId\\"}
     *
     * @var string
     */
    public $customTraceConfig;

    /**
     * @description The list of custom configuration items.
     *
     * @example removeResponseServerHeader
     *
     * @var string
     */
    public $customerConfigs;

    /**
     * @description The type of exclusive instance where the group is located
     *
     * - Traditional type exclusive instance: normal
     * @example normal
     *
     * @var string
     */
    public $dedicatedInstanceType;

    /**
     * @description The default domain name.
     *
     * @example mkt.api.gaore.com
     *
     * @var string
     */
    public $defaultDomain;

    /**
     * @description The description of the API group.
     *
     * @example New weather informations.
     *
     * @var string
     */
    public $description;

    /**
     * @description Indicates whether access over the public second-level domain name is enabled. Valid values:
     *
     *   true
     *   false
     *
     * @example false
     *
     * @var bool
     */
    public $disableInnerDomain;

    /**
     * @description The ID of the API group. This ID is generated by the system and globally unique.
     *
     * @example 523e8dc7bbe04613b5b1d726c2a7889d
     *
     * @var string
     */
    public $groupId;

    /**
     * @description The name of the group to which the API belongs.
     *
     * @example NewWeather
     *
     * @var string
     */
    public $groupName;

    /**
     * @description The HTTPS policy.
     *
     * @example HTTPS2_TLS1_0
     *
     * @var string
     */
    public $httpsPolicy;

    /**
     * @description The validity status of the API group. Valid values:
     *
     *   **NORMAL**: The API group is normal.
     *   **LOCKED**: The API group is locked because it is not valid.
     *
     * @example NORMAL
     *
     * @var string
     */
    public $illegalStatus;

    /**
     * @description The ID of the instance.
     *
     * @example apigateway-cn-v6419k43xxxxx
     *
     * @var string
     */
    public $instanceId;

    /**
     * @description The type of the instance.
     *
     *   CLASSIC_SHARED: shared instance that uses the classic network configuration
     *   VPC_SHARED: shared instance that uses VPC
     *   VPC_DEDICATED: dedicated instance that uses VPC
     *
     * @example VPC_SHARED
     *
     * @var string
     */
    public $instanceType;

    /**
     * @description The IPv6 status.
     *
     * @example UNBIND
     *
     * @var string
     */
    public $ipv6Status;

    /**
     * @description The reason for the failure of the group migration instance task. When the value of the MigrationStatus parameter is Failed, it is not empty.
     *
     * @example The current instance conflicts with the target instance.
     *
     * @var string
     */
    public $migrationError;

    /**
     * @description Group migration instance task status
     *
     * - Failed
     * @example Fail
     *
     * @var string
     */
    public $migrationStatus;

    /**
     * @description The last modification time (UTC) of the API group.
     *
     * @example 2016-08-01T06:54:32Z
     *
     * @var string
     */
    public $modifiedTime;

    /**
     * @description Specifies whether to pass headers.
     *
     * @example eagleeye-rpcid,x-b3-traceid
     *
     * @var string
     */
    public $passthroughHeaders;

    /**
     * @description The region to which the API group belongs.
     *
     * @example cn-hangzhou
     *
     * @var string
     */
    public $regionId;

    /**
     * @description The ID of the request.
     *
     * @example 03442A3D-3B7D-434C-8A95-A5FEB989B519
     *
     * @var string
     */
    public $requestId;

    /**
     * @description The runtime environment information.
     *
     * @var stageItems
     */
    public $stageItems;

    /**
     * @description The status of the API group.
     *
     *   **NORMAL**: The API group is normal.
     *   **DELETE**: The API group is deleted.
     *
     * @example NORMAL
     *
     * @var string
     */
    public $status;

    /**
     * @description The second-level domain name automatically assigned to the API group.
     *
     * @example 27d50c0f2e54b359919923d908bb015-cn-hangzhou.alicloudapi.com
     *
     * @var string
     */
    public $subDomain;

    /**
     * @description The upper QPS limit of the API group. The default value is 500. You can increase the upper limit by submitting an application.
     *
     * @example 500
     *
     * @var int
     */
    public $trafficLimit;

    /**
     * @description The user log settings.
     *
     * @example {\\"requestBody\\":true,\\"responseBody\\":true,\\"queryString\\":\\"test\\",\\"requestHeaders\\":\\"test\\",\\"responseHeaders\\":\\"test\\",\\"jwtClaims\\":\\"test\\"}
     *
     * @var string
     */
    public $userLogConfig;

    /**
     * @description The VPC domain name.
     *
     * @example e4****7151954***acbd9f7****1058a-ap-southeast-1-vpc.alicloudapi.com
     *
     * @var string
     */
    public $vpcDomain;

    /**
     * @description The VPC SLB domain name.
     *
     * @example 257e9d450e924d00b976b0ecfb7184c2-cn-beijing-intranet.alicloudapi.com
     *
     * @var string
     */
    public $vpcSlbIntranetDomain;
    protected $_name = [
        'basePath'              => 'BasePath',
        'billingStatus'         => 'BillingStatus',
        'cloudMarketCommodity'  => 'CloudMarketCommodity',
        'cmsMonitorGroup'       => 'CmsMonitorGroup',
        'compatibleFlags'       => 'CompatibleFlags',
        'createdTime'           => 'CreatedTime',
        'customDomains'         => 'CustomDomains',
        'customTraceConfig'     => 'CustomTraceConfig',
        'customerConfigs'       => 'CustomerConfigs',
        'dedicatedInstanceType' => 'DedicatedInstanceType',
        'defaultDomain'         => 'DefaultDomain',
        'description'           => 'Description',
        'disableInnerDomain'    => 'DisableInnerDomain',
        'groupId'               => 'GroupId',
        'groupName'             => 'GroupName',
        'httpsPolicy'           => 'HttpsPolicy',
        'illegalStatus'         => 'IllegalStatus',
        'instanceId'            => 'InstanceId',
        'instanceType'          => 'InstanceType',
        'ipv6Status'            => 'Ipv6Status',
        'migrationError'        => 'MigrationError',
        'migrationStatus'       => 'MigrationStatus',
        'modifiedTime'          => 'ModifiedTime',
        'passthroughHeaders'    => 'PassthroughHeaders',
        'regionId'              => 'RegionId',
        'requestId'             => 'RequestId',
        'stageItems'            => 'StageItems',
        'status'                => 'Status',
        'subDomain'             => 'SubDomain',
        'trafficLimit'          => 'TrafficLimit',
        'userLogConfig'         => 'UserLogConfig',
        'vpcDomain'             => 'VpcDomain',
        'vpcSlbIntranetDomain'  => 'VpcSlbIntranetDomain',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->basePath) {
            $res['BasePath'] = $this->basePath;
        }
        if (null !== $this->billingStatus) {
            $res['BillingStatus'] = $this->billingStatus;
        }
        if (null !== $this->cloudMarketCommodity) {
            $res['CloudMarketCommodity'] = $this->cloudMarketCommodity;
        }
        if (null !== $this->cmsMonitorGroup) {
            $res['CmsMonitorGroup'] = $this->cmsMonitorGroup;
        }
        if (null !== $this->compatibleFlags) {
            $res['CompatibleFlags'] = $this->compatibleFlags;
        }
        if (null !== $this->createdTime) {
            $res['CreatedTime'] = $this->createdTime;
        }
        if (null !== $this->customDomains) {
            $res['CustomDomains'] = null !== $this->customDomains ? $this->customDomains->toMap() : null;
        }
        if (null !== $this->customTraceConfig) {
            $res['CustomTraceConfig'] = $this->customTraceConfig;
        }
        if (null !== $this->customerConfigs) {
            $res['CustomerConfigs'] = $this->customerConfigs;
        }
        if (null !== $this->dedicatedInstanceType) {
            $res['DedicatedInstanceType'] = $this->dedicatedInstanceType;
        }
        if (null !== $this->defaultDomain) {
            $res['DefaultDomain'] = $this->defaultDomain;
        }
        if (null !== $this->description) {
            $res['Description'] = $this->description;
        }
        if (null !== $this->disableInnerDomain) {
            $res['DisableInnerDomain'] = $this->disableInnerDomain;
        }
        if (null !== $this->groupId) {
            $res['GroupId'] = $this->groupId;
        }
        if (null !== $this->groupName) {
            $res['GroupName'] = $this->groupName;
        }
        if (null !== $this->httpsPolicy) {
            $res['HttpsPolicy'] = $this->httpsPolicy;
        }
        if (null !== $this->illegalStatus) {
            $res['IllegalStatus'] = $this->illegalStatus;
        }
        if (null !== $this->instanceId) {
            $res['InstanceId'] = $this->instanceId;
        }
        if (null !== $this->instanceType) {
            $res['InstanceType'] = $this->instanceType;
        }
        if (null !== $this->ipv6Status) {
            $res['Ipv6Status'] = $this->ipv6Status;
        }
        if (null !== $this->migrationError) {
            $res['MigrationError'] = $this->migrationError;
        }
        if (null !== $this->migrationStatus) {
            $res['MigrationStatus'] = $this->migrationStatus;
        }
        if (null !== $this->modifiedTime) {
            $res['ModifiedTime'] = $this->modifiedTime;
        }
        if (null !== $this->passthroughHeaders) {
            $res['PassthroughHeaders'] = $this->passthroughHeaders;
        }
        if (null !== $this->regionId) {
            $res['RegionId'] = $this->regionId;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->stageItems) {
            $res['StageItems'] = null !== $this->stageItems ? $this->stageItems->toMap() : null;
        }
        if (null !== $this->status) {
            $res['Status'] = $this->status;
        }
        if (null !== $this->subDomain) {
            $res['SubDomain'] = $this->subDomain;
        }
        if (null !== $this->trafficLimit) {
            $res['TrafficLimit'] = $this->trafficLimit;
        }
        if (null !== $this->userLogConfig) {
            $res['UserLogConfig'] = $this->userLogConfig;
        }
        if (null !== $this->vpcDomain) {
            $res['VpcDomain'] = $this->vpcDomain;
        }
        if (null !== $this->vpcSlbIntranetDomain) {
            $res['VpcSlbIntranetDomain'] = $this->vpcSlbIntranetDomain;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return DescribeApiGroupResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['BasePath'])) {
            $model->basePath = $map['BasePath'];
        }
        if (isset($map['BillingStatus'])) {
            $model->billingStatus = $map['BillingStatus'];
        }
        if (isset($map['CloudMarketCommodity'])) {
            $model->cloudMarketCommodity = $map['CloudMarketCommodity'];
        }
        if (isset($map['CmsMonitorGroup'])) {
            $model->cmsMonitorGroup = $map['CmsMonitorGroup'];
        }
        if (isset($map['CompatibleFlags'])) {
            $model->compatibleFlags = $map['CompatibleFlags'];
        }
        if (isset($map['CreatedTime'])) {
            $model->createdTime = $map['CreatedTime'];
        }
        if (isset($map['CustomDomains'])) {
            $model->customDomains = customDomains::fromMap($map['CustomDomains']);
        }
        if (isset($map['CustomTraceConfig'])) {
            $model->customTraceConfig = $map['CustomTraceConfig'];
        }
        if (isset($map['CustomerConfigs'])) {
            $model->customerConfigs = $map['CustomerConfigs'];
        }
        if (isset($map['DedicatedInstanceType'])) {
            $model->dedicatedInstanceType = $map['DedicatedInstanceType'];
        }
        if (isset($map['DefaultDomain'])) {
            $model->defaultDomain = $map['DefaultDomain'];
        }
        if (isset($map['Description'])) {
            $model->description = $map['Description'];
        }
        if (isset($map['DisableInnerDomain'])) {
            $model->disableInnerDomain = $map['DisableInnerDomain'];
        }
        if (isset($map['GroupId'])) {
            $model->groupId = $map['GroupId'];
        }
        if (isset($map['GroupName'])) {
            $model->groupName = $map['GroupName'];
        }
        if (isset($map['HttpsPolicy'])) {
            $model->httpsPolicy = $map['HttpsPolicy'];
        }
        if (isset($map['IllegalStatus'])) {
            $model->illegalStatus = $map['IllegalStatus'];
        }
        if (isset($map['InstanceId'])) {
            $model->instanceId = $map['InstanceId'];
        }
        if (isset($map['InstanceType'])) {
            $model->instanceType = $map['InstanceType'];
        }
        if (isset($map['Ipv6Status'])) {
            $model->ipv6Status = $map['Ipv6Status'];
        }
        if (isset($map['MigrationError'])) {
            $model->migrationError = $map['MigrationError'];
        }
        if (isset($map['MigrationStatus'])) {
            $model->migrationStatus = $map['MigrationStatus'];
        }
        if (isset($map['ModifiedTime'])) {
            $model->modifiedTime = $map['ModifiedTime'];
        }
        if (isset($map['PassthroughHeaders'])) {
            $model->passthroughHeaders = $map['PassthroughHeaders'];
        }
        if (isset($map['RegionId'])) {
            $model->regionId = $map['RegionId'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['StageItems'])) {
            $model->stageItems = stageItems::fromMap($map['StageItems']);
        }
        if (isset($map['Status'])) {
            $model->status = $map['Status'];
        }
        if (isset($map['SubDomain'])) {
            $model->subDomain = $map['SubDomain'];
        }
        if (isset($map['TrafficLimit'])) {
            $model->trafficLimit = $map['TrafficLimit'];
        }
        if (isset($map['UserLogConfig'])) {
            $model->userLogConfig = $map['UserLogConfig'];
        }
        if (isset($map['VpcDomain'])) {
            $model->vpcDomain = $map['VpcDomain'];
        }
        if (isset($map['VpcSlbIntranetDomain'])) {
            $model->vpcSlbIntranetDomain = $map['VpcSlbIntranetDomain'];
        }

        return $model;
    }
}
