<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\DescribeIdcProbeListResponseBody\idcProbes;
use AlibabaCloud\SDK\Sas\V20181203\Models\DescribeIdcProbeListResponseBody\pageInfo;
use AlibabaCloud\Tea\Model;

class DescribeIdcProbeListResponseBody extends Model
{
    /**
     * @description IDC probe list.
     *
     * @var idcProbes[]
     */
    public $idcProbes;

    /**
     * @description Pagination information.
     *
     * @var pageInfo
     */
    public $pageInfo;

    /**
     * @description The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting and problem localization.
     *
     * @example 0C8487EF-50C2-54BB-8634-10F8C35D****
     *
     * @var string
     */
    public $requestId;
    protected $_name = [
        'idcProbes' => 'IdcProbes',
        'pageInfo'  => 'PageInfo',
        'requestId' => 'RequestId',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->idcProbes) {
            $res['IdcProbes'] = [];
            if (null !== $this->idcProbes && \is_array($this->idcProbes)) {
                $n = 0;
                foreach ($this->idcProbes as $item) {
                    $res['IdcProbes'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }
        if (null !== $this->pageInfo) {
            $res['PageInfo'] = null !== $this->pageInfo ? $this->pageInfo->toMap() : null;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return DescribeIdcProbeListResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['IdcProbes'])) {
            if (!empty($map['IdcProbes'])) {
                $model->idcProbes = [];
                $n                = 0;
                foreach ($map['IdcProbes'] as $item) {
                    $model->idcProbes[$n++] = null !== $item ? idcProbes::fromMap($item) : $item;
                }
            }
        }
        if (isset($map['PageInfo'])) {
            $model->pageInfo = pageInfo::fromMap($map['PageInfo']);
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }

        return $model;
    }
}
