<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\GetDockerhubImageRiskRankInfoResponseBody\riskRankInfo;
use AlibabaCloud\Tea\Model;

class GetDockerhubImageRiskRankInfoResponseBody extends Model
{
    /**
     * @description The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used for troubleshooting and problem localization.
     *
     * @example 30CBF632-109F-596F-97F2-451C8B2A****
     *
     * @var string
     */
    public $requestId;

    /**
     * @description Risk information.
     *
     * @var riskRankInfo
     */
    public $riskRankInfo;
    protected $_name = [
        'requestId' => 'RequestId',
        'riskRankInfo' => 'RiskRankInfo',
    ];

    public function validate() {}

    public function toMap()
    {
        $res = [];
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->riskRankInfo) {
            $res['RiskRankInfo'] = null !== $this->riskRankInfo ? $this->riskRankInfo->toMap() : null;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return GetDockerhubImageRiskRankInfoResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['RiskRankInfo'])) {
            $model->riskRankInfo = riskRankInfo::fromMap($map['RiskRankInfo']);
        }

        return $model;
    }
}
