<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\GetInstallCodeForUuidResponseBody\installCode;
use AlibabaCloud\Tea\Model;

class GetInstallCodeForUuidResponseBody extends Model
{
    /**
     * @description API status code.
     *
     * @example 200
     *
     * @var int
     */
    public $code;

    /**
     * @description HTTP status code
     *
     * @example 200
     *
     * @var int
     */
    public $httpStatusCode;

    /**
     * @description Client installation code.
     *
     * @var installCode
     */
    public $installCode;

    /**
     * @description Response message from the request.
     *
     * @example successful
     *
     * @var string
     */
    public $message;

    /**
     * @description The ID of the current request, a unique identifier generated by Alibaba Cloud for troubleshooting and issue localization.
     *
     * @example 7532B7EE-7CE7-5F4D-BF04-B12447DDCAE1
     *
     * @var string
     */
    public $requestId;

    /**
     * @description The status of the returned query result. Values: - **true**: Success - **false**: Failure
     *
     * @example true
     *
     * @var bool
     */
    public $success;
    protected $_name = [
        'code' => 'Code',
        'httpStatusCode' => 'HttpStatusCode',
        'installCode' => 'InstallCode',
        'message' => 'Message',
        'requestId' => 'RequestId',
        'success' => 'Success',
    ];

    public function validate() {}

    public function toMap()
    {
        $res = [];
        if (null !== $this->code) {
            $res['Code'] = $this->code;
        }
        if (null !== $this->httpStatusCode) {
            $res['HttpStatusCode'] = $this->httpStatusCode;
        }
        if (null !== $this->installCode) {
            $res['InstallCode'] = null !== $this->installCode ? $this->installCode->toMap() : null;
        }
        if (null !== $this->message) {
            $res['Message'] = $this->message;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->success) {
            $res['Success'] = $this->success;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return GetInstallCodeForUuidResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['Code'])) {
            $model->code = $map['Code'];
        }
        if (isset($map['HttpStatusCode'])) {
            $model->httpStatusCode = $map['HttpStatusCode'];
        }
        if (isset($map['InstallCode'])) {
            $model->installCode = installCode::fromMap($map['InstallCode']);
        }
        if (isset($map['Message'])) {
            $model->message = $map['Message'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['Success'])) {
            $model->success = $map['Success'];
        }

        return $model;
    }
}
