<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\ListCheckRuleResponseBody\checkRules;
use AlibabaCloud\SDK\Sas\V20181203\Models\ListCheckRuleResponseBody\pageInfo;
use AlibabaCloud\Tea\Model;

class ListCheckRuleResponseBody extends Model
{
    /**
     * @description Check rules.
     *
     * @var checkRules[]
     */
    public $checkRules;

    /**
     * @description Pagination information.
     *
     * @var pageInfo
     */
    public $pageInfo;

    /**
     * @description The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request. It can be used for troubleshooting and problem localization.
     *
     * @example 52870893-48A7-5A9E-9E05-6253E5B6****
     *
     * @var string
     */
    public $requestId;
    protected $_name = [
        'checkRules' => 'CheckRules',
        'pageInfo'   => 'PageInfo',
        'requestId'  => 'RequestId',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->checkRules) {
            $res['CheckRules'] = [];
            if (null !== $this->checkRules && \is_array($this->checkRules)) {
                $n = 0;
                foreach ($this->checkRules as $item) {
                    $res['CheckRules'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }
        if (null !== $this->pageInfo) {
            $res['PageInfo'] = null !== $this->pageInfo ? $this->pageInfo->toMap() : null;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return ListCheckRuleResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['CheckRules'])) {
            if (!empty($map['CheckRules'])) {
                $model->checkRules = [];
                $n                 = 0;
                foreach ($map['CheckRules'] as $item) {
                    $model->checkRules[$n++] = null !== $item ? checkRules::fromMap($item) : $item;
                }
            }
        }
        if (isset($map['PageInfo'])) {
            $model->pageInfo = pageInfo::fromMap($map['PageInfo']);
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }

        return $model;
    }
}
