<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\ListTargetByBatchResponseBody\pageInfo;
use AlibabaCloud\Tea\Model;

class ListTargetByBatchResponseBody extends Model
{
    /**
     * @description Pagination information.
     *
     * @var pageInfo
     */
    public $pageInfo;

    /**
     * @description The ID of the request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
     *
     * @example 6EBB8614-746D-555D-AB69-C801AEC7DCE0
     *
     * @var string
     */
    public $requestId;

    /**
     * @description The returned list.
     *
     * @var string[]
     */
    public $targetList;
    protected $_name = [
        'pageInfo' => 'PageInfo',
        'requestId' => 'RequestId',
        'targetList' => 'TargetList',
    ];

    public function validate() {}

    public function toMap()
    {
        $res = [];
        if (null !== $this->pageInfo) {
            $res['PageInfo'] = null !== $this->pageInfo ? $this->pageInfo->toMap() : null;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->targetList) {
            $res['TargetList'] = $this->targetList;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return ListTargetByBatchResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['PageInfo'])) {
            $model->pageInfo = pageInfo::fromMap($map['PageInfo']);
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['TargetList'])) {
            if (!empty($map['TargetList'])) {
                $model->targetList = $map['TargetList'];
            }
        }

        return $model;
    }
}
