<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\Tea\Model;

class ListUuidsByAppIdResponseBody extends Model
{
    /**
     * @description Total number of data entries.
     *
     * @example 1
     *
     * @var int
     */
    public $count;

    /**
     * @description The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and pinpoint issues.
     *
     * @example 1383B0DB-D5D6-4B0C-9E6B-75939C8E****
     *
     * @var string
     */
    public $requestId;

    /**
     * @description List of UUIDs.
     *
     * @var string[]
     */
    public $uuids;
    protected $_name = [
        'count' => 'Count',
        'requestId' => 'RequestId',
        'uuids' => 'Uuids',
    ];

    public function validate() {}

    public function toMap()
    {
        $res = [];
        if (null !== $this->count) {
            $res['Count'] = $this->count;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->uuids) {
            $res['Uuids'] = $this->uuids;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return ListUuidsByAppIdResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['Count'])) {
            $model->count = $map['Count'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['Uuids'])) {
            if (!empty($map['Uuids'])) {
                $model->uuids = $map['Uuids'];
            }
        }

        return $model;
    }
}
