<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\SDK\Sas\V20181203\Models\ListImageRegistryExtraResponseBody\imageRegistryExtraInfos;
use AlibabaCloud\Tea\Model;

class ListImageRegistryExtraResponseBody extends Model
{
    /**
     * @description Additional configuration information for the image registry.
     *
     * @var imageRegistryExtraInfos[]
     */
    public $imageRegistryExtraInfos;

    /**
     * @description The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot and locate issues.
     *
     * @example 09969D2C-4FAD-429E-BFBF-9A60DEF8****
     *
     * @var string
     */
    public $requestId;
    protected $_name = [
        'imageRegistryExtraInfos' => 'ImageRegistryExtraInfos',
        'requestId'               => 'RequestId',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->imageRegistryExtraInfos) {
            $res['ImageRegistryExtraInfos'] = [];
            if (null !== $this->imageRegistryExtraInfos && \is_array($this->imageRegistryExtraInfos)) {
                $n = 0;
                foreach ($this->imageRegistryExtraInfos as $item) {
                    $res['ImageRegistryExtraInfos'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return ListImageRegistryExtraResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['ImageRegistryExtraInfos'])) {
            if (!empty($map['ImageRegistryExtraInfos'])) {
                $model->imageRegistryExtraInfos = [];
                $n                              = 0;
                foreach ($map['ImageRegistryExtraInfos'] as $item) {
                    $model->imageRegistryExtraInfos[$n++] = null !== $item ? imageRegistryExtraInfos::fromMap($item) : $item;
                }
            }
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }

        return $model;
    }
}
