<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Sas\V20181203\Models;

use AlibabaCloud\Tea\Model;

class OpenBackupAutoConfigRequest extends Model
{
    /**
     * @description The number of servers specified in a batch of anti-ransomware policies that are automatically generated by the managed anti-ransomware feature.
     *
     * >  The maximum value is 50. If the number of specified servers exceeds 50, the value 50 is used.
     * @example 20
     *
     * @var int
     */
    public $maxBatchSize;
    protected $_name = [
        'maxBatchSize' => 'MaxBatchSize',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->maxBatchSize) {
            $res['MaxBatchSize'] = $this->maxBatchSize;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return OpenBackupAutoConfigRequest
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['MaxBatchSize'])) {
            $model->maxBatchSize = $map['MaxBatchSize'];
        }

        return $model;
    }
}
