<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Dts\V20200101\Models;

use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeSubscriptionInstanceStatusResponseBody\sourceEndpoint;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeSubscriptionInstanceStatusResponseBody\subscriptionDataType;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeSubscriptionInstanceStatusResponseBody\subscriptionHost;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeSubscriptionInstanceStatusResponseBody\subscriptionObject;
use AlibabaCloud\Tea\Model;

class DescribeSubscriptionInstanceStatusResponseBody extends Model
{
    /**
     * @description The start of the time range for change tracking. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
     *
     * @example 2021-03-15T08:25:34Z
     *
     * @var string
     */
    public $beginTimestamp;

    /**
     * @description The consumption checkpoint of the change tracking instance. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
     *
     * @example 2021-03-23T07:30:31Z
     *
     * @var string
     */
    public $consumptionCheckpoint;

    /**
     * @description The downstream client information, in the following format: \\<IP address of the downstream client>:\\<Random ID generated by DTS>.
     *
     * @example 114.***.***.**:dts********
     *
     * @var string
     */
    public $consumptionClient;

    /**
     * @description The end of the time range for change tracking. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
     *
     * @example 2021-03-26T14:03:21Z
     *
     * @var string
     */
    public $endTimestamp;

    /**
     * @description The error code returned if the call failed.
     *
     * @example InternalError
     *
     * @var string
     */
    public $errCode;

    /**
     * @description The error message returned if the call failed.
     *
     * @example The request processing has failed due to some unknown error.
     *
     * @var string
     */
    public $errMessage;

    /**
     * @description The error message returned if change tracking failed.
     *
     * @example ******
     *
     * @var string
     */
    public $errorMessage;

    /**
     * @description The billing method of the change tracking instance. Valid values:
     *
     *   **PrePaid**: subscription
     *   **PostPaid**: pay-as-you-go
     *
     * @example PrePaid
     *
     * @var string
     */
    public $payType;

    /**
     * @description The ID of the request.
     *
     * @example E0845D0A-6D36-4EEB-BE26-CF191E1A****
     *
     * @var string
     */
    public $requestId;

    /**
     * @description The connection settings of the source instance.
     *
     * @var sourceEndpoint
     */
    public $sourceEndpoint;

    /**
     * @description The status of the change tracking task. Valid values:
     *
     *   **NotStarted**: The task is not started.
     *   **Prechecking**: The task is being prechecked.
     *   **PrecheckFailed**: The task failed to pass the precheck.
     *   **Starting**: The task is being started.
     *   **Normal**: The task is running as expected.
     *   **Abnormal**: The task is not running as expected.
     *
     * @example Normal
     *
     * @var string
     */
    public $status;

    /**
     * @description The topic of the change tracking instance.
     *
     * >  This parameter is returned only if your change tracking instance is of the new version and you have called the [CreateConsumerGroup](https://help.aliyun.com/document_detail/122863.html) operation to create a consumer group.
     * @example cn_hangzhou_rm_bp1162kryivb8****_dtstest_version2
     *
     * @var string
     */
    public $subscribeTopic;

    /**
     * @description The types of operations that are tracked by the task.
     *
     * @var subscriptionDataType
     */
    public $subscriptionDataType;

    /**
     * @description The endpoint of the change tracking instance.
     *
     * @var subscriptionHost
     */
    public $subscriptionHost;

    /**
     * @description The ID of the change tracking instance.
     *
     * @example rm-bp1162kryivb8****
     *
     * @var string
     */
    public $subscriptionInstanceID;

    /**
     * @description The name of the change tracking instance.
     *
     * @var string
     */
    public $subscriptionInstanceName;

    /**
     * @description The objects for change tracking.
     *
     * @var subscriptionObject
     */
    public $subscriptionObject;

    /**
     * @description Indicates whether the call was successful.
     *
     * @example true
     *
     * @var string
     */
    public $success;

    /**
     * @description The ID of the change tracking task.
     *
     * @example y0zz3t13h7d****
     *
     * @var string
     */
    public $taskId;
    protected $_name = [
        'beginTimestamp'           => 'BeginTimestamp',
        'consumptionCheckpoint'    => 'ConsumptionCheckpoint',
        'consumptionClient'        => 'ConsumptionClient',
        'endTimestamp'             => 'EndTimestamp',
        'errCode'                  => 'ErrCode',
        'errMessage'               => 'ErrMessage',
        'errorMessage'             => 'ErrorMessage',
        'payType'                  => 'PayType',
        'requestId'                => 'RequestId',
        'sourceEndpoint'           => 'SourceEndpoint',
        'status'                   => 'Status',
        'subscribeTopic'           => 'SubscribeTopic',
        'subscriptionDataType'     => 'SubscriptionDataType',
        'subscriptionHost'         => 'SubscriptionHost',
        'subscriptionInstanceID'   => 'SubscriptionInstanceID',
        'subscriptionInstanceName' => 'SubscriptionInstanceName',
        'subscriptionObject'       => 'SubscriptionObject',
        'success'                  => 'Success',
        'taskId'                   => 'TaskId',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->beginTimestamp) {
            $res['BeginTimestamp'] = $this->beginTimestamp;
        }
        if (null !== $this->consumptionCheckpoint) {
            $res['ConsumptionCheckpoint'] = $this->consumptionCheckpoint;
        }
        if (null !== $this->consumptionClient) {
            $res['ConsumptionClient'] = $this->consumptionClient;
        }
        if (null !== $this->endTimestamp) {
            $res['EndTimestamp'] = $this->endTimestamp;
        }
        if (null !== $this->errCode) {
            $res['ErrCode'] = $this->errCode;
        }
        if (null !== $this->errMessage) {
            $res['ErrMessage'] = $this->errMessage;
        }
        if (null !== $this->errorMessage) {
            $res['ErrorMessage'] = $this->errorMessage;
        }
        if (null !== $this->payType) {
            $res['PayType'] = $this->payType;
        }
        if (null !== $this->requestId) {
            $res['RequestId'] = $this->requestId;
        }
        if (null !== $this->sourceEndpoint) {
            $res['SourceEndpoint'] = null !== $this->sourceEndpoint ? $this->sourceEndpoint->toMap() : null;
        }
        if (null !== $this->status) {
            $res['Status'] = $this->status;
        }
        if (null !== $this->subscribeTopic) {
            $res['SubscribeTopic'] = $this->subscribeTopic;
        }
        if (null !== $this->subscriptionDataType) {
            $res['SubscriptionDataType'] = null !== $this->subscriptionDataType ? $this->subscriptionDataType->toMap() : null;
        }
        if (null !== $this->subscriptionHost) {
            $res['SubscriptionHost'] = null !== $this->subscriptionHost ? $this->subscriptionHost->toMap() : null;
        }
        if (null !== $this->subscriptionInstanceID) {
            $res['SubscriptionInstanceID'] = $this->subscriptionInstanceID;
        }
        if (null !== $this->subscriptionInstanceName) {
            $res['SubscriptionInstanceName'] = $this->subscriptionInstanceName;
        }
        if (null !== $this->subscriptionObject) {
            $res['SubscriptionObject'] = null !== $this->subscriptionObject ? $this->subscriptionObject->toMap() : null;
        }
        if (null !== $this->success) {
            $res['Success'] = $this->success;
        }
        if (null !== $this->taskId) {
            $res['TaskId'] = $this->taskId;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return DescribeSubscriptionInstanceStatusResponseBody
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['BeginTimestamp'])) {
            $model->beginTimestamp = $map['BeginTimestamp'];
        }
        if (isset($map['ConsumptionCheckpoint'])) {
            $model->consumptionCheckpoint = $map['ConsumptionCheckpoint'];
        }
        if (isset($map['ConsumptionClient'])) {
            $model->consumptionClient = $map['ConsumptionClient'];
        }
        if (isset($map['EndTimestamp'])) {
            $model->endTimestamp = $map['EndTimestamp'];
        }
        if (isset($map['ErrCode'])) {
            $model->errCode = $map['ErrCode'];
        }
        if (isset($map['ErrMessage'])) {
            $model->errMessage = $map['ErrMessage'];
        }
        if (isset($map['ErrorMessage'])) {
            $model->errorMessage = $map['ErrorMessage'];
        }
        if (isset($map['PayType'])) {
            $model->payType = $map['PayType'];
        }
        if (isset($map['RequestId'])) {
            $model->requestId = $map['RequestId'];
        }
        if (isset($map['SourceEndpoint'])) {
            $model->sourceEndpoint = sourceEndpoint::fromMap($map['SourceEndpoint']);
        }
        if (isset($map['Status'])) {
            $model->status = $map['Status'];
        }
        if (isset($map['SubscribeTopic'])) {
            $model->subscribeTopic = $map['SubscribeTopic'];
        }
        if (isset($map['SubscriptionDataType'])) {
            $model->subscriptionDataType = subscriptionDataType::fromMap($map['SubscriptionDataType']);
        }
        if (isset($map['SubscriptionHost'])) {
            $model->subscriptionHost = subscriptionHost::fromMap($map['SubscriptionHost']);
        }
        if (isset($map['SubscriptionInstanceID'])) {
            $model->subscriptionInstanceID = $map['SubscriptionInstanceID'];
        }
        if (isset($map['SubscriptionInstanceName'])) {
            $model->subscriptionInstanceName = $map['SubscriptionInstanceName'];
        }
        if (isset($map['SubscriptionObject'])) {
            $model->subscriptionObject = subscriptionObject::fromMap($map['SubscriptionObject']);
        }
        if (isset($map['Success'])) {
            $model->success = $map['Success'];
        }
        if (isset($map['TaskId'])) {
            $model->taskId = $map['TaskId'];
        }

        return $model;
    }
}
