<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Edas\V20170801\Models\ListSubAccountResponseBody\subAccountList;

use AlibabaCloud\Tea\Model;

class subAccount extends Model
{
    /**
     * @description The ID of the Alibaba Cloud account. This ID is generated by EDAS.
     *
     * @example 12456889****
     *
     * @var string
     */
    public $adminEdasId;

    /**
     * @description The ID of the Alibaba Cloud account.
     *
     * @example test@13624697***
     *
     * @var string
     */
    public $adminUserId;

    /**
     * @description This parameter is the same as the AdminEdasId parameter. This parameter is deprecated.
     *
     * @example 12456889****
     *
     * @var string
     */
    public $adminUserKp;

    /**
     * @description The email address of the RAM user.
     *
     * @example email@aliyun.com
     *
     * @var string
     */
    public $email;

    /**
     * @description The contact information of the RAM user.
     *
     * @example 1373322****
     *
     * @var string
     */
    public $phone;

    /**
     * @description The ID of the RAM user. This ID is generated by Enterprise Distributed Application Service (EDAS).
     *
     * @example 28382009411268****
     *
     * @var string
     */
    public $subEdasId;

    /**
     * @description The ID of the RAM user.
     *
     * @example ram1@117274586608****
     *
     * @var string
     */
    public $subUserId;

    /**
     * @description This parameter is the same as the SubEdasId parameter. This parameter is deprecated.
     *
     * @example 28382009411268****
     *
     * @var string
     */
    public $subUserKp;
    protected $_name = [
        'adminEdasId' => 'AdminEdasId',
        'adminUserId' => 'AdminUserId',
        'adminUserKp' => 'AdminUserKp',
        'email'       => 'Email',
        'phone'       => 'Phone',
        'subEdasId'   => 'SubEdasId',
        'subUserId'   => 'SubUserId',
        'subUserKp'   => 'SubUserKp',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->adminEdasId) {
            $res['AdminEdasId'] = $this->adminEdasId;
        }
        if (null !== $this->adminUserId) {
            $res['AdminUserId'] = $this->adminUserId;
        }
        if (null !== $this->adminUserKp) {
            $res['AdminUserKp'] = $this->adminUserKp;
        }
        if (null !== $this->email) {
            $res['Email'] = $this->email;
        }
        if (null !== $this->phone) {
            $res['Phone'] = $this->phone;
        }
        if (null !== $this->subEdasId) {
            $res['SubEdasId'] = $this->subEdasId;
        }
        if (null !== $this->subUserId) {
            $res['SubUserId'] = $this->subUserId;
        }
        if (null !== $this->subUserKp) {
            $res['SubUserKp'] = $this->subUserKp;
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return subAccount
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['AdminEdasId'])) {
            $model->adminEdasId = $map['AdminEdasId'];
        }
        if (isset($map['AdminUserId'])) {
            $model->adminUserId = $map['AdminUserId'];
        }
        if (isset($map['AdminUserKp'])) {
            $model->adminUserKp = $map['AdminUserKp'];
        }
        if (isset($map['Email'])) {
            $model->email = $map['Email'];
        }
        if (isset($map['Phone'])) {
            $model->phone = $map['Phone'];
        }
        if (isset($map['SubEdasId'])) {
            $model->subEdasId = $map['SubEdasId'];
        }
        if (isset($map['SubUserId'])) {
            $model->subUserId = $map['SubUserId'];
        }
        if (isset($map['SubUserKp'])) {
            $model->subUserKp = $map['SubUserKp'];
        }

        return $model;
    }
}
