<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody;

use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\dataCloudStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\dataEtlStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\dataInitializationStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\dataSynchronizationStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\destinationEndpoint;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\errorDetails;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\fullDataCheckStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\incDataCheckStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\migrationMode;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\performance;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\precheckStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\retryState;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\reverseJob;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\sourceEndpoint;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\structureInitializationStatus;
use AlibabaCloud\SDK\Dts\V20200101\Models\DescribeDtsJobsResponseBody\dtsJobList\tagList;
use AlibabaCloud\Tea\Model;

class dtsJobList extends Model
{
    /**
     * @description Indicates whether the **new** change tracking feature is used.
     *
     * >  This parameter is returned only for change tracking instances of the new version.
     * @example new
     *
     * @var string
     */
    public $appName;

    /**
     * @description The start of the time range for change tracking. The time follows the ISO 8601 standard in the *yyyy-MM-dd*T*HH:mm:ss*Z format. The time is displayed in UTC.
     *
     * @example 2021-03-15T08:25:34Z
     *
     * @var string
     */
    public $beginTimestamp;

    /**
     * @description The start offset of incremental data synchronization. The value is a UNIX timestamp representing the number of seconds that have elapsed since the epoch time January 1, 1970, 00:00:00 UTC.
     *
     * @example 1616899019
     *
     * @var string
     */
    public $checkpoint;

    /**
     * @description The consumption checkpoint of the change tracking instance. The time follows the ISO 8601 standard in the *yyyy-MM-dd*T*HH:mm:ss*Z format. The time is displayed in UTC.
     *
     * @example 2021-03-23T07:30:31Z
     *
     * @var string
     */
    public $consumptionCheckpoint;

    /**
     * @description The downstream client information, in the following format: \\<IP address of the downstream client>:\\<Random ID generated by DTS>.
     *
     * @example 114...:dts******
     *
     * @var string
     */
    public $consumptionClient;

    /**
     * @description The CPU utilization of the instance. Unit: percentage.
     *
     * @example 1
     *
     * @var string
     */
    public $cpuUsage;

    /**
     * @description The point in time when the task was created. The time follows the ISO 8601 standard in the *yyyy-MM-dd*T*HH:mm:ss*Z format. The time is displayed in UTC.
     *
     * @example 2021-03-16T08:01:19Z
     *
     * @var string
     */
    public $createTime;

    /**
     * @description The state of the physical gateway-based migration task.
     *
     * @var dataCloudStatus
     */
    public $dataCloudStatus;

    /**
     * @description The state of the extract, transform, and load (ETL) task. Valid values:
     *
     * >  This parameter collection is returned only if an ETL task is configured.
     * @var dataEtlStatus
     */
    public $dataEtlStatus;

    /**
     * @description The state of full data synchronization.
     *
     * @var dataInitializationStatus
     */
    public $dataInitializationStatus;

    /**
     * @description The state of incremental data migration or synchronization.
     *
     * @var dataSynchronizationStatus
     */
    public $dataSynchronizationStatus;

    /**
     * @description The objects that you want to synchronize. The value is a JSON string and can contain regular expressions. For more information, see "Objects of DTS tasks".
     *
     * @example {"dtstestdata": { "name": "dtstestdata", "all": true }}
     *
     * @var string
     */
    public $dbObject;

    /**
     * @description The ID of the DTS dedicated cluster on which a DTS task runs.
     *
     * @example dtscluster_ft7y3**********
     *
     * @var string
     */
    public $dedicatedClusterId;

    /**
     * @description The latency of incremental data synchronization. Unit: seconds.
     *
     * @example 0
     *
     * @var int
     */
    public $delay;

    /**
     * @description The connection settings of the destination instance.
     *
     * @var destinationEndpoint
     */
    public $destinationEndpoint;

    /**
     * @description The environment tag of the DTS instance. Valid values:
     *
     * - **normal**
     * - **online**
     * @example normal
     *
     * @var string
     */
    public $dtsBisLabel;

    /**
     * @description The ID of the data synchronization instance.
     *
     * @example dtsi03e3zty16i****
     *
     * @var string
     */
    public $dtsInstanceID;

    /**
     * @description The instance class.
     *
     * >  For more information about the test performance of each instance class, see [Specifications of data synchronization instances](https://help.aliyun.com/document_detail/26605.html).
     * @example large
     *
     * @var string
     */
    public $dtsJobClass;

    /**
     * @description The synchronization direction. The value is **Reverse**.
     *
     * @example Forward
     *
     * @var string
     */
    public $dtsJobDirection;

    /**
     * @description The ID of the data synchronization task.
     *
     * @example i03e3zty16i****
     *
     * @var string
     */
    public $dtsJobId;

    /**
     * @description The name of the data synchronization task.
     *
     * @example RDS_TO_RDS_MIGRATION
     *
     * @var string
     */
    public $dtsJobName;

    /**
     * @description The number of DUs that have been used.
     *
     * @example 15
     *
     * @var int
     */
    public $duUsage;

    /**
     * @description The end of the time range for change tracking. The time follows the ISO 8601 standard in the *yyyy-MM-dd*T*HH:mm:ss*Z format. The time is displayed in UTC.
     *
     * @example 2021-03-26T14:03:21Z
     *
     * @var string
     */
    public $endTimestamp;

    /**
     * @description The error message returned.
     *
     * @var errorDetails[]
     */
    public $errorDetails;

    /**
     * @description The error message returned if the task failed.
     *
     * @example DTS-070211: Connect Source DB failed. cause by [com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException:Could not create connection to database server. Attempted reconnect 3 times. Giving up.][com.mysql.jdbc.exceptions.jdbc4.CommunicationsException:Communications link failure\\n\\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.][java.net.ConnectException:Connection timed out (Connection timed out)] About more information in [https://yq.aliyun.com/articles/499178].
     *
     * @var string
     */
    public $errorMessage;

    /**
     * @description The checkpoint of the ETL task.
     *
     * @example 1610540493
     *
     * @var string
     */
    public $etlSafeCheckpoint;

    /**
     * @description The point in time when the instance expires. The time follows the ISO 8601 standard in the *yyyy-MM-dd*T*HH:mm:ss*Z format. The time is displayed in UTC.
     *
     * >  This parameter is returned only if the value of the **PayType** parameter is **PrePaid**.
     * @example 2022-03-16T08:01:19Z
     *
     * @var string
     */
    public $expireTime;

    /**
     * @description The state information about the full data verification task.
     *
     * @var fullDataCheckStatus
     */
    public $fullDataCheckStatus;

    /**
     * @description The state information about the incremental data verification task.
     *
     * @var incDataCheckStatus
     */
    public $incDataCheckStatus;

    /**
     * @description The type of the DTS task. Valid values:
     *
     * - **MIGRATION**: data migration task
     * - **SYNC**: data synchronization task
     * - **SUBSCRIBE**: change tracking task
     * @example MIGRATION
     *
     * @var string
     */
    public $jobType;

    /**
     * @var float
     */
    public $maxDu;

    /**
     * @description The memory that has been used. Unit: MB.
     *
     * @example 500
     *
     * @var string
     */
    public $memUsage;

    /**
     * @description The error code.
     *
     * @example dts.retry.err.0046
     *
     * @var string
     */
    public $migrationErrCode;

    /**
     * @description The ID of the error code-related documentation.
     *
     * @example 462133
     *
     * @var string
     */
    public $migrationErrHelpDocId;

    /**
     * @description The key of the error code-related documentation.
     *
     * @example DTS-RETRY-ERR-0046
     *
     * @var string
     */
    public $migrationErrHelpDocKey;

    /**
     * @description The error message.
     *
     * @example dts.retry.err.0046.msg
     *
     * @var string
     */
    public $migrationErrMsg;

    /**
     * @description The type of the error code.
     *
     * @example ForeignKey
     *
     * @var string
     */
    public $migrationErrType;

    /**
     * @description The solution to the error.
     *
     * @example dts.retry.err.0046.workaround
     *
     * @var string
     */
    public $migrationErrWorkaround;

    /**
     * @description The migration or synchronization modes.
     *
     * @var migrationMode
     */
    public $migrationMode;

    /**
     * @var float
     */
    public $minDu;

    /**
     * @description The source of the task. Valid values:
     *
     *   **PTS**
     *   **DMS**
     *   **DTS**
     *
     * @example DTS
     *
     * @var string
     */
    public $originType;

    /**
     * @description The billing method of the DTS instance. Valid values:
     *
     *   **PrePaid**: subscription
     *   **PostPaid**: pay-as-you-go
     *
     * @example PrePaid
     *
     * @var string
     */
    public $payType;

    /**
     * @description The performance of the data migration or synchronization instance.
     *
     * @var performance
     */
    public $performance;

    /**
     * @description The precheck state.
     *
     * @var precheckStatus
     */
    public $precheckStatus;

    /**
     * @description The reserved parameter of DTS. The value is a JSON string. You can specify this parameter to meet specific requirements, for example, whether to automatically start a precheck. For more information, see [MigrationReserved](https://help.aliyun.com/document_detail/176470.html).
     *
     * @example {\\"srcHostPorts\\":\\"\\",\\"whitelist.dms.online.ddl.enable\\":false,\\"filterDDL\\":false,\\"sqlparser.dms.original.ddl\\":true,\\"srcOracleType\\":\\"sid\\",\\"maxRetryTime\\":43200,\\"destSSL\\":\\"0\\",\\"destOracleType\\":\\"sid\\",\\"srcSSL\\":\\"0\\",\\"dbListCaseChangeMode\\":\\"default\\",\\"SourceEngineVersion\\":\\"8.0.18\\",\\"srcNetType\\":\\"VPC\\",\\"destNetType\\":\\"VPC\\",\\"srcVpcNetMappingInst\\":\\"172.16.1**.**:10803\\",\\"destVpcNetMappingInst\\":\\"172.16.1**.**:11077\\",\\"useJobTask\\":\\"1\\"}
     *
     * @var string
     */
    public $reserved;

    /**
     * @description The name of the resource group.
     *
     * @example default resource group
     *
     * @var string
     */
    public $resourceGroupDisplayName;

    /**
     * @description The resource group ID.
     *
     * @example rg-acfmzawhxxc****
     *
     * @var string
     */
    public $resourceGroupId;

    /**
     * @description The information about the retries performed by DTS due to an exception.
     *
     * @var retryState
     */
    public $retryState;

    /**
     * @description The details of the data synchronization task in the reverse direction.
     *
     * > This parameter is returned only for two-way data synchronization tasks.
     * @var reverseJob
     */
    public $reverseJob;

    /**
     * @description The connection settings of the source instance.
     *
     * @var sourceEndpoint
     */
    public $sourceEndpoint;

    /**
     * @description The state of the DTS instance. For more information about the valid values, see the description of the request parameter **Status**.
     *
     * @example Migrating
     *
     * @var string
     */
    public $status;

    /**
     * @description The state of schema migration or initial schema synchronization.
     *
     * @var structureInitializationStatus
     */
    public $structureInitializationStatus;

    /**
     * @description The tags of the task.
     *
     * @var tagList[]
     */
    public $tagList;
    protected $_name = [
        'appName'                       => 'AppName',
        'beginTimestamp'                => 'BeginTimestamp',
        'checkpoint'                    => 'Checkpoint',
        'consumptionCheckpoint'         => 'ConsumptionCheckpoint',
        'consumptionClient'             => 'ConsumptionClient',
        'cpuUsage'                      => 'CpuUsage',
        'createTime'                    => 'CreateTime',
        'dataCloudStatus'               => 'DataCloudStatus',
        'dataEtlStatus'                 => 'DataEtlStatus',
        'dataInitializationStatus'      => 'DataInitializationStatus',
        'dataSynchronizationStatus'     => 'DataSynchronizationStatus',
        'dbObject'                      => 'DbObject',
        'dedicatedClusterId'            => 'DedicatedClusterId',
        'delay'                         => 'Delay',
        'destinationEndpoint'           => 'DestinationEndpoint',
        'dtsBisLabel'                   => 'DtsBisLabel',
        'dtsInstanceID'                 => 'DtsInstanceID',
        'dtsJobClass'                   => 'DtsJobClass',
        'dtsJobDirection'               => 'DtsJobDirection',
        'dtsJobId'                      => 'DtsJobId',
        'dtsJobName'                    => 'DtsJobName',
        'duUsage'                       => 'DuUsage',
        'endTimestamp'                  => 'EndTimestamp',
        'errorDetails'                  => 'ErrorDetails',
        'errorMessage'                  => 'ErrorMessage',
        'etlSafeCheckpoint'             => 'EtlSafeCheckpoint',
        'expireTime'                    => 'ExpireTime',
        'fullDataCheckStatus'           => 'FullDataCheckStatus',
        'incDataCheckStatus'            => 'IncDataCheckStatus',
        'jobType'                       => 'JobType',
        'maxDu'                         => 'MaxDu',
        'memUsage'                      => 'MemUsage',
        'migrationErrCode'              => 'MigrationErrCode',
        'migrationErrHelpDocId'         => 'MigrationErrHelpDocId',
        'migrationErrHelpDocKey'        => 'MigrationErrHelpDocKey',
        'migrationErrMsg'               => 'MigrationErrMsg',
        'migrationErrType'              => 'MigrationErrType',
        'migrationErrWorkaround'        => 'MigrationErrWorkaround',
        'migrationMode'                 => 'MigrationMode',
        'minDu'                         => 'MinDu',
        'originType'                    => 'OriginType',
        'payType'                       => 'PayType',
        'performance'                   => 'Performance',
        'precheckStatus'                => 'PrecheckStatus',
        'reserved'                      => 'Reserved',
        'resourceGroupDisplayName'      => 'ResourceGroupDisplayName',
        'resourceGroupId'               => 'ResourceGroupId',
        'retryState'                    => 'RetryState',
        'reverseJob'                    => 'ReverseJob',
        'sourceEndpoint'                => 'SourceEndpoint',
        'status'                        => 'Status',
        'structureInitializationStatus' => 'StructureInitializationStatus',
        'tagList'                       => 'TagList',
    ];

    public function validate()
    {
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->appName) {
            $res['AppName'] = $this->appName;
        }
        if (null !== $this->beginTimestamp) {
            $res['BeginTimestamp'] = $this->beginTimestamp;
        }
        if (null !== $this->checkpoint) {
            $res['Checkpoint'] = $this->checkpoint;
        }
        if (null !== $this->consumptionCheckpoint) {
            $res['ConsumptionCheckpoint'] = $this->consumptionCheckpoint;
        }
        if (null !== $this->consumptionClient) {
            $res['ConsumptionClient'] = $this->consumptionClient;
        }
        if (null !== $this->cpuUsage) {
            $res['CpuUsage'] = $this->cpuUsage;
        }
        if (null !== $this->createTime) {
            $res['CreateTime'] = $this->createTime;
        }
        if (null !== $this->dataCloudStatus) {
            $res['DataCloudStatus'] = null !== $this->dataCloudStatus ? $this->dataCloudStatus->toMap() : null;
        }
        if (null !== $this->dataEtlStatus) {
            $res['DataEtlStatus'] = null !== $this->dataEtlStatus ? $this->dataEtlStatus->toMap() : null;
        }
        if (null !== $this->dataInitializationStatus) {
            $res['DataInitializationStatus'] = null !== $this->dataInitializationStatus ? $this->dataInitializationStatus->toMap() : null;
        }
        if (null !== $this->dataSynchronizationStatus) {
            $res['DataSynchronizationStatus'] = null !== $this->dataSynchronizationStatus ? $this->dataSynchronizationStatus->toMap() : null;
        }
        if (null !== $this->dbObject) {
            $res['DbObject'] = $this->dbObject;
        }
        if (null !== $this->dedicatedClusterId) {
            $res['DedicatedClusterId'] = $this->dedicatedClusterId;
        }
        if (null !== $this->delay) {
            $res['Delay'] = $this->delay;
        }
        if (null !== $this->destinationEndpoint) {
            $res['DestinationEndpoint'] = null !== $this->destinationEndpoint ? $this->destinationEndpoint->toMap() : null;
        }
        if (null !== $this->dtsBisLabel) {
            $res['DtsBisLabel'] = $this->dtsBisLabel;
        }
        if (null !== $this->dtsInstanceID) {
            $res['DtsInstanceID'] = $this->dtsInstanceID;
        }
        if (null !== $this->dtsJobClass) {
            $res['DtsJobClass'] = $this->dtsJobClass;
        }
        if (null !== $this->dtsJobDirection) {
            $res['DtsJobDirection'] = $this->dtsJobDirection;
        }
        if (null !== $this->dtsJobId) {
            $res['DtsJobId'] = $this->dtsJobId;
        }
        if (null !== $this->dtsJobName) {
            $res['DtsJobName'] = $this->dtsJobName;
        }
        if (null !== $this->duUsage) {
            $res['DuUsage'] = $this->duUsage;
        }
        if (null !== $this->endTimestamp) {
            $res['EndTimestamp'] = $this->endTimestamp;
        }
        if (null !== $this->errorDetails) {
            $res['ErrorDetails'] = [];
            if (null !== $this->errorDetails && \is_array($this->errorDetails)) {
                $n = 0;
                foreach ($this->errorDetails as $item) {
                    $res['ErrorDetails'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }
        if (null !== $this->errorMessage) {
            $res['ErrorMessage'] = $this->errorMessage;
        }
        if (null !== $this->etlSafeCheckpoint) {
            $res['EtlSafeCheckpoint'] = $this->etlSafeCheckpoint;
        }
        if (null !== $this->expireTime) {
            $res['ExpireTime'] = $this->expireTime;
        }
        if (null !== $this->fullDataCheckStatus) {
            $res['FullDataCheckStatus'] = null !== $this->fullDataCheckStatus ? $this->fullDataCheckStatus->toMap() : null;
        }
        if (null !== $this->incDataCheckStatus) {
            $res['IncDataCheckStatus'] = null !== $this->incDataCheckStatus ? $this->incDataCheckStatus->toMap() : null;
        }
        if (null !== $this->jobType) {
            $res['JobType'] = $this->jobType;
        }
        if (null !== $this->maxDu) {
            $res['MaxDu'] = $this->maxDu;
        }
        if (null !== $this->memUsage) {
            $res['MemUsage'] = $this->memUsage;
        }
        if (null !== $this->migrationErrCode) {
            $res['MigrationErrCode'] = $this->migrationErrCode;
        }
        if (null !== $this->migrationErrHelpDocId) {
            $res['MigrationErrHelpDocId'] = $this->migrationErrHelpDocId;
        }
        if (null !== $this->migrationErrHelpDocKey) {
            $res['MigrationErrHelpDocKey'] = $this->migrationErrHelpDocKey;
        }
        if (null !== $this->migrationErrMsg) {
            $res['MigrationErrMsg'] = $this->migrationErrMsg;
        }
        if (null !== $this->migrationErrType) {
            $res['MigrationErrType'] = $this->migrationErrType;
        }
        if (null !== $this->migrationErrWorkaround) {
            $res['MigrationErrWorkaround'] = $this->migrationErrWorkaround;
        }
        if (null !== $this->migrationMode) {
            $res['MigrationMode'] = null !== $this->migrationMode ? $this->migrationMode->toMap() : null;
        }
        if (null !== $this->minDu) {
            $res['MinDu'] = $this->minDu;
        }
        if (null !== $this->originType) {
            $res['OriginType'] = $this->originType;
        }
        if (null !== $this->payType) {
            $res['PayType'] = $this->payType;
        }
        if (null !== $this->performance) {
            $res['Performance'] = null !== $this->performance ? $this->performance->toMap() : null;
        }
        if (null !== $this->precheckStatus) {
            $res['PrecheckStatus'] = null !== $this->precheckStatus ? $this->precheckStatus->toMap() : null;
        }
        if (null !== $this->reserved) {
            $res['Reserved'] = $this->reserved;
        }
        if (null !== $this->resourceGroupDisplayName) {
            $res['ResourceGroupDisplayName'] = $this->resourceGroupDisplayName;
        }
        if (null !== $this->resourceGroupId) {
            $res['ResourceGroupId'] = $this->resourceGroupId;
        }
        if (null !== $this->retryState) {
            $res['RetryState'] = null !== $this->retryState ? $this->retryState->toMap() : null;
        }
        if (null !== $this->reverseJob) {
            $res['ReverseJob'] = null !== $this->reverseJob ? $this->reverseJob->toMap() : null;
        }
        if (null !== $this->sourceEndpoint) {
            $res['SourceEndpoint'] = null !== $this->sourceEndpoint ? $this->sourceEndpoint->toMap() : null;
        }
        if (null !== $this->status) {
            $res['Status'] = $this->status;
        }
        if (null !== $this->structureInitializationStatus) {
            $res['StructureInitializationStatus'] = null !== $this->structureInitializationStatus ? $this->structureInitializationStatus->toMap() : null;
        }
        if (null !== $this->tagList) {
            $res['TagList'] = [];
            if (null !== $this->tagList && \is_array($this->tagList)) {
                $n = 0;
                foreach ($this->tagList as $item) {
                    $res['TagList'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return dtsJobList
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['AppName'])) {
            $model->appName = $map['AppName'];
        }
        if (isset($map['BeginTimestamp'])) {
            $model->beginTimestamp = $map['BeginTimestamp'];
        }
        if (isset($map['Checkpoint'])) {
            $model->checkpoint = $map['Checkpoint'];
        }
        if (isset($map['ConsumptionCheckpoint'])) {
            $model->consumptionCheckpoint = $map['ConsumptionCheckpoint'];
        }
        if (isset($map['ConsumptionClient'])) {
            $model->consumptionClient = $map['ConsumptionClient'];
        }
        if (isset($map['CpuUsage'])) {
            $model->cpuUsage = $map['CpuUsage'];
        }
        if (isset($map['CreateTime'])) {
            $model->createTime = $map['CreateTime'];
        }
        if (isset($map['DataCloudStatus'])) {
            $model->dataCloudStatus = dataCloudStatus::fromMap($map['DataCloudStatus']);
        }
        if (isset($map['DataEtlStatus'])) {
            $model->dataEtlStatus = dataEtlStatus::fromMap($map['DataEtlStatus']);
        }
        if (isset($map['DataInitializationStatus'])) {
            $model->dataInitializationStatus = dataInitializationStatus::fromMap($map['DataInitializationStatus']);
        }
        if (isset($map['DataSynchronizationStatus'])) {
            $model->dataSynchronizationStatus = dataSynchronizationStatus::fromMap($map['DataSynchronizationStatus']);
        }
        if (isset($map['DbObject'])) {
            $model->dbObject = $map['DbObject'];
        }
        if (isset($map['DedicatedClusterId'])) {
            $model->dedicatedClusterId = $map['DedicatedClusterId'];
        }
        if (isset($map['Delay'])) {
            $model->delay = $map['Delay'];
        }
        if (isset($map['DestinationEndpoint'])) {
            $model->destinationEndpoint = destinationEndpoint::fromMap($map['DestinationEndpoint']);
        }
        if (isset($map['DtsBisLabel'])) {
            $model->dtsBisLabel = $map['DtsBisLabel'];
        }
        if (isset($map['DtsInstanceID'])) {
            $model->dtsInstanceID = $map['DtsInstanceID'];
        }
        if (isset($map['DtsJobClass'])) {
            $model->dtsJobClass = $map['DtsJobClass'];
        }
        if (isset($map['DtsJobDirection'])) {
            $model->dtsJobDirection = $map['DtsJobDirection'];
        }
        if (isset($map['DtsJobId'])) {
            $model->dtsJobId = $map['DtsJobId'];
        }
        if (isset($map['DtsJobName'])) {
            $model->dtsJobName = $map['DtsJobName'];
        }
        if (isset($map['DuUsage'])) {
            $model->duUsage = $map['DuUsage'];
        }
        if (isset($map['EndTimestamp'])) {
            $model->endTimestamp = $map['EndTimestamp'];
        }
        if (isset($map['ErrorDetails'])) {
            if (!empty($map['ErrorDetails'])) {
                $model->errorDetails = [];
                $n                   = 0;
                foreach ($map['ErrorDetails'] as $item) {
                    $model->errorDetails[$n++] = null !== $item ? errorDetails::fromMap($item) : $item;
                }
            }
        }
        if (isset($map['ErrorMessage'])) {
            $model->errorMessage = $map['ErrorMessage'];
        }
        if (isset($map['EtlSafeCheckpoint'])) {
            $model->etlSafeCheckpoint = $map['EtlSafeCheckpoint'];
        }
        if (isset($map['ExpireTime'])) {
            $model->expireTime = $map['ExpireTime'];
        }
        if (isset($map['FullDataCheckStatus'])) {
            $model->fullDataCheckStatus = fullDataCheckStatus::fromMap($map['FullDataCheckStatus']);
        }
        if (isset($map['IncDataCheckStatus'])) {
            $model->incDataCheckStatus = incDataCheckStatus::fromMap($map['IncDataCheckStatus']);
        }
        if (isset($map['JobType'])) {
            $model->jobType = $map['JobType'];
        }
        if (isset($map['MaxDu'])) {
            $model->maxDu = $map['MaxDu'];
        }
        if (isset($map['MemUsage'])) {
            $model->memUsage = $map['MemUsage'];
        }
        if (isset($map['MigrationErrCode'])) {
            $model->migrationErrCode = $map['MigrationErrCode'];
        }
        if (isset($map['MigrationErrHelpDocId'])) {
            $model->migrationErrHelpDocId = $map['MigrationErrHelpDocId'];
        }
        if (isset($map['MigrationErrHelpDocKey'])) {
            $model->migrationErrHelpDocKey = $map['MigrationErrHelpDocKey'];
        }
        if (isset($map['MigrationErrMsg'])) {
            $model->migrationErrMsg = $map['MigrationErrMsg'];
        }
        if (isset($map['MigrationErrType'])) {
            $model->migrationErrType = $map['MigrationErrType'];
        }
        if (isset($map['MigrationErrWorkaround'])) {
            $model->migrationErrWorkaround = $map['MigrationErrWorkaround'];
        }
        if (isset($map['MigrationMode'])) {
            $model->migrationMode = migrationMode::fromMap($map['MigrationMode']);
        }
        if (isset($map['MinDu'])) {
            $model->minDu = $map['MinDu'];
        }
        if (isset($map['OriginType'])) {
            $model->originType = $map['OriginType'];
        }
        if (isset($map['PayType'])) {
            $model->payType = $map['PayType'];
        }
        if (isset($map['Performance'])) {
            $model->performance = performance::fromMap($map['Performance']);
        }
        if (isset($map['PrecheckStatus'])) {
            $model->precheckStatus = precheckStatus::fromMap($map['PrecheckStatus']);
        }
        if (isset($map['Reserved'])) {
            $model->reserved = $map['Reserved'];
        }
        if (isset($map['ResourceGroupDisplayName'])) {
            $model->resourceGroupDisplayName = $map['ResourceGroupDisplayName'];
        }
        if (isset($map['ResourceGroupId'])) {
            $model->resourceGroupId = $map['ResourceGroupId'];
        }
        if (isset($map['RetryState'])) {
            $model->retryState = retryState::fromMap($map['RetryState']);
        }
        if (isset($map['ReverseJob'])) {
            $model->reverseJob = reverseJob::fromMap($map['ReverseJob']);
        }
        if (isset($map['SourceEndpoint'])) {
            $model->sourceEndpoint = sourceEndpoint::fromMap($map['SourceEndpoint']);
        }
        if (isset($map['Status'])) {
            $model->status = $map['Status'];
        }
        if (isset($map['StructureInitializationStatus'])) {
            $model->structureInitializationStatus = structureInitializationStatus::fromMap($map['StructureInitializationStatus']);
        }
        if (isset($map['TagList'])) {
            if (!empty($map['TagList'])) {
                $model->tagList = [];
                $n              = 0;
                foreach ($map['TagList'] as $item) {
                    $model->tagList[$n++] = null !== $item ? tagList::fromMap($item) : $item;
                }
            }
        }

        return $model;
    }
}
